### ISSUE TITLE
Updating link to "Scheme: An Interpreter for Extended Lambda Calculus"

### ISSUE THREAD

**Issue by aos** [hellerve/ptolemy#5]
Hey Veit. Thanks for the reading list -- these are great.

Just a heads up, the link to **Scheme: An Interpreter for Extended Lambda Calculus** is dead. 

[I used the wayback machine to grab the closest live link here](https://web.archive.org/web/20171025111456/http://repository.readscheme.org/ftp/papers/ai-lab-pubs/AIM-349.pdf). Too lazy to send a PR, sorry :P

**Comment by hellerve** [comment]
Hey @aos, thanks for the heads-up and for sniffing out an alternative! I’ve updated the link.

I assume this will happen a bunch with papers I’ve read, since I don’t really often come back to check on the links. A little sad, but alright.

**Comment by aos** [comment]
Of course :-) It is a bit sad, agreed! If I happen to run into another one I'll let you know.
